version: "3.8"

networks:
  backbone:
    driver: bridge
    # external: true

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: seeandyougo
      MYSQL_ROOT_PASSWORD: seeandyougo
      MYSQL_USER: seeandyougo
      MYSQL_PASSWORD: seeandyougo
      TZ: 'Asia/Seoul'
      LC_ALL: C.UTF-8
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
       - backbone
  seeandyougo:
    container_name: seeandyougo
    build:
      context: ./backend
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - backbone
    depends_on:
       - mysql
    environment:
      - TZ=Asia/Seoul
  seeandyougo-nginx:
    container_name: seeandyougo-nginx
    build: .
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443"
    networks:
      - backbone
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - seeandyougo