spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(H9pUTzJxUaoznblkCPNXfAUjsd6G5folC0vshVow/4dBeEdRtDHEwNAILi8klFXA+fowtnLIMooR0H3ozkCE/2CYaivK/fssb/0ArwNIZHGoMAZUUtdhwGLhgxLPELN8iNIGJHJ5jd6OExpFB/tF2Q==)
    username: ENC(VAWmf0MkWD4xPJ2zOGPWOHvyajcKuVeQR3jy/tFy6WRpNWHz2vwLGE6zr14yGxVu)
    password: ENC(JFvsq3nAt6n+ox8HbNBbjts1rTSHt4pgFYDpcZ7DeXFT+54hrrEB8+qsn6XMns1H)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ENC(s0kY/BCuYxVpbDUFfGHpmvAgaMCx/nu3esTKuqMpHux6jkPQCY2C5s3hNUL9r2CH)
      port: ENC(GJTSm9A/fFkT3pMbSOgy/6dySCYY+bqVKBgorDKTrcBOOotPMCagsCliZrjfsoCN)

external-api:
  menu:
    save:
      url: https://api.cnu.ac.kr
      endpoint: /svc/offcam/pub/FoodInfo
  connection:
    save:
      url: https://api.cnu.ac.kr
      endpoint: /svc/offcam/pub/WifiAllInfo
