spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/seeandyougo?useSSL=false&allowPublicKeyRetrieval=true
    username: seeandyougo
    password: seeandyougo
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

URL:
  CONN_URL: https://api.cnu.ac.kr/svc/offcam/pub/WifiAllInfo
  DISH_URL: https://api.cnu.ac.kr/svc/offcam/pub/FoodInfo
