spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/seeandyougo?useSSL=false&allowPublicKeyRetrieval=true
    username: seeandyougo
    password: seeandyougo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis
      port: 6379

DISH:
  SAVE:
    URL: https://seeandyougo-mock-server.onrender.com
    END_POINT: /svc/offcam/pub/FoodInfo

CONN:
  SAVE:
    URL: https://seeandyougo-mock-server.onrender.com
    END_POINT: /svc/offcam/pub/WifiAllInfo
